### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by crushgh** [seethroughdev/obsidian-recipe-grabber#1]
This is not in the community plugins directory and doesn't seem to work with BRAT - which says that main.js is missing?

**Comment by seethroughdev** [comment]
Hi, its in the review process at the moment, I just updated the release here: https://github.com/seethroughdev/obsidian-recipe-grabber/releases/tag/0.10.0

That should include the main.js and other assets as well.

**Comment by seethroughdev** [comment]
Just learned about BRAT. Will dig into why its not working there too.

**Comment by seethroughdev** [comment]
Okay, I think release was in draft still. Fixed, and confirmed plugin loads and works with BRAT.

**Comment by seethroughdev** [comment]
plugin is now available through Community Plugins and confirmed works with BRAT as well.
