### ISSUE TITLE
Feature request: save recipe json

### ISSUE THREAD

**Issue by cathelijne** [seethroughdev/obsidian-recipe-grabber#12]
As someone who eventually wants to publish the recipes I've grabbed, it would be great if the grabbed json is available after parsing.

Just a download would be great already. This seems easy and if I wasn't such a klutz with anything that resembles javascript I could probably do that myself.

Nice-to-haves:
- choose download folder
- switch saving on or off

**Comment by seethroughdev** [comment]
Not sure about implementing a separate save here. I could maybe have a settings option that pastes the snippet that includes the json inline?

**Comment by cathelijne** [comment]
That sounds like great idea too! I think my main wish is for the JSON to end up somewhere, and this would definitely work.

**Comment by cathelijne** [comment]
The `{{{json}}}` tag in the handlebars template works beautifully. Thank you so much!

**Comment by seethroughdev** [comment]
Great. Also, just note. The JSON can be slightly modified from the original as we have to do a lot of work to normalize them. So if you're publishing and need the original, you'd likely want to go to the site for it.
