### ISSUE TITLE
Ability to use {{date}} and {{time}}

### ISSUE THREAD

**Issue by lzilioli** [seethroughdev/obsidian-recipe-grabber#16]
The existing obsidian functionality provides the means to reference todays date and time when inserting a template. This would be a welcome addition to this plugin as well. Ideally this plugin could hook into my existing formatting config for date and time.

**Comment by seethroughdev** [comment]
Makes sense. I would think escaping the line in handlebars would prevent the conflict. `\{{date}}` but it just renders inside the file as `{{date}}`. 

I'm not sure how/when the templater looks for those tags in the internals. Open to other ideas here.

**Comment by seethroughdev** [comment]
This feature is now in! More info here: https://github.com/seethroughdev/obsidian-recipe-grabber/pull/25#issuecomment-2051377877
