### ISSUE TITLE
Not working. How to use?

### ISSUE THREAD

**Issue by Gourav1910** [seethroughdev/obsidian-recipe-grabber#2]
Hi I just installed your plugin and paste a link of an random article but nothing happened. Please clear the instructions in your readme page about how to use this plugin and what kind of links we should paste. The video/gif you uploaded in the readme page is also not working.

**Comment by seethroughdev** [comment]
Hi @Gourav1910 , so sorry about the confusion.

I updated the video link, and it does appear to be working. Please let me know if you have any issues. I also did a clean install from the community plugin, and it does appear to be working for me like the video.

To use: Click the `chef` hat to activate the plugin, it should create a popup that has an input for a webpage. 

<img width="380" alt="Screenshot 2023-06-30 at 2 55 33 PM" src="https://github.com/seethroughdev/obsidian-recipe-grabber/assets/203779/17a40590-1a97-4a36-9e42-092a12c3bfc3">

Any recipe url that has a [Recipe Schema](https://schema.org/Recipe) should work. In my experience, most of them do. So it shouldn't be an issue.

After you paste the URL, just click `Get Recipe` and it should paste the contents directly into the currently open page.

Please let me know if you're able to get it working. Thanks.

**Comment by Gourav1910** [comment]
> Any issues here still? Or okay to close?

Yeah it is working but not bringing all the data properly. But I think it's the fault of plugin but may be article lacking various information or what you call recipe schema. Yeah you can close it.

**Comment by seethroughdev** [comment]
Yeah, that is possible. Can you send any examples though? If there's a way to improve the parsing, I definitely will.

**Comment by seethroughdev** [comment]
Point is still valid, but not much i can do for now, since we're dependent on the schema data.
