### ISSUE TITLE
Error message for zeinaskitchen.se

### ISSUE THREAD

**Issue by notanovel** [seethroughdev/obsidian-recipe-grabber#28]
Hi,

The plugin works like a charm on 99% of the pages I'm using but somehow it can't pull any info from this homepage here, [here's an example recipe](https://zeinaskitchen.se/lasagne-i-stekpanna/).

The error message I get is "recipe scheme not found".

Is there anything that can be done about it?

**Comment by seethroughdev** [comment]
Glad to hear its working for you. The way the plugin works is it looks for [Recipe Schemas](https://schema.org/Recipe) embedded in the page. The page you linked doesn't have a Recipe Schema it could read, so unfortunately, it can't grab the recipe. 

This is a helpful tool to see if it has a readable schema or not: https://validator.schema.org/#url=https%3A%2F%2Fzeinaskitchen.se%2Flasagne-i-stekpanna%2F

Hope that helps!

**Comment by seethroughdev** [comment]
Closing issue. Feel free to add anymore comments if you feel like there's more we can do here. Thanks.

**Comment by notanovel** [comment]
Apologies for getting back only now - thanks for the validation link and thanks for taking the time to answer!
