### ISSUE TITLE
Does not work if tab is in Reading mode

### ISSUE THREAD

**Issue by Ovyerus** [seethroughdev/obsidian-recipe-grabber#29]
I was having a bunch of trouble with the plugin seemingly being completely broken and just creating blank files with no error popups or in the console. Had an idea today to try switch "Default view for new tabs" back to Editing instead of Reading and it works fine.

Dug through the plugin code quickly and found what I suspect to be the cause: assuming that there is an editor instance open.

https://github.com/seethroughdev/obsidian-recipe-grabber/blob/330823bc999a4ef8e5b12f59847eb9b05c3f34d3/src/main.ts#L362-L367

Perhaps [`Vault.append`](https://docs.obsidian.md/Reference/TypeScript+API/Vault/append) should be used instead of manipulating the editor?

**Comment by seethroughdev** [comment]
Sorry for the delay in responding here, @Ovyerus . This makes perfect sense, and your PR is really appreciated! Will follow up in the PR. Thank you again!
