### ISSUE TITLE
Create new file

### ISSUE THREAD

**Issue by ispringle** [seethroughdev/obsidian-recipe-grabber#4]
Wondering if there could be an option to create a new file when grabbing a recipe, and optionally in a specific folder as well.

**Comment by seethroughdev** [comment]
Thanks for the feedback @ispringle . I think I could definitely do a check to see if there's an active document and if not, then open a new one. but the folder selection brings up a good point. 

let me look into this a bit further. keep you updated.

**Comment by nickian** [comment]
That would be great. As well as an option in the settings to set a folder the new file is saved to.

**Comment by seethroughdev** [comment]
So sorry for the delay here. I just added this to the latest version. However, it will just create a new file in the current vault directory, and you can move it anywhere you like. Hope that's still helpful!

**Comment by seethroughdev** [comment]
The [proper fix here](https://github.com/seethroughdev/obsidian-recipe-grabber/pull/18) is in and will go out in the next release!
