### ISSUE TITLE
Add support for https://www.closetcooking.com/

### ISSUE THREAD

**Issue by adambuchweitz** [seethroughdev/obsidian-recipe-grabber#40]
They have good recipes, and mostly seem to follow the correct pattern. Bonus points for fixing title casing!

## Example recipe
[Mexican Stuffed Peppers](https://www.closetcooking.com/mexican-stuffed-peppers/)
Prep Time: 20 minutes Cook Time: 50 minutes Total Time: 1 hour 10 minutes Servings: 8
Mexican themed stuffed peppers with taco seasoned beef, quinoa, beans, corn, tomatoes and plenty of melted cheese!

ingredients
1/2 cup quinoa
1 cup water
1 pound ground beef
1 onion, diced
1 tablespoon taco seasoning (or one package)
1/2 cup water
1 (14.5 ounce) can black beans, rinsed and drained
1 (14.5 ounce) can diced tomatoes (or 1 cup salsa)
1 cup corn
4 bell peppers, cut in half and seeds removed
1 cup enchilada sauce (or 1 (14.5 ounce) can enchilada sauce) (optional)
2 cups cheese (cheddar and/or monterey jack), shredded
1/2 cup cilantro lime crema (with and without the roasted jalapenos)
1 cup pico de gallo (with and without jalapenos)
1 cup guacamole(with and without jalapenos)
1/4 cup queso fresco (or feta) crumbled
directions
Bring the water and quinoa to a boil, reduce the heat and simmer, covered, until the quinoa is tender and the liquid has all been absorbed, about 15 minutes, before letting it sit, covered, for 5 minutes, and then letting it cool.
Meanwhile cook the beef and onions in a large pan over medium-high heat until browned, breaking it apart as it cooks, before draining off any excess grease.
Add the taco seasoning and water, mix, bring to a boil, reduce the heat and simmer until the liquid has cooked off.
Mix the meat, quinoa, beans, corn and tomatoes and stuff it into the peppers.
Spread the enchilada sauce over the bottom of one of more baking pans, place the peppers in and sprinkle on the cheese.
Bake in a preheated 350F/180C oven until the cheese has melted, the peppers are tender and the sauce is bubbling, about 30-40 minutes.
Serve the stuffed peppers in a bed of the sauce, topped with the roasted jalapeno crema with the pico de gallo and guacamole on the side.
Option: The heat in the stuffed peppers is controlled by the taco seasoning which you can use more of or less of as desired, optionally splitting the filling in half with different amounts of seasoning.
Tip: Cook the quinoa a day ahead.
Tip: Make any or all of the roasted jalapeno crema, pico de gallo and guacamole a day ahead of time.
Option: Make and assemble the stuffed peppers the day before and simply bake on the day that they are to be enjoyed.
Note: These stuffed peppers freeze well and can easily be reheated!
Note: The enchilada sauce is optional and you can simply oil the baking pan and bake the stuffed pepper without the sauce.
Tip: Use any leftover filling to make burritos!
Nutrition Facts: Calories 460, Fat 26g (Saturated 12g, Trans 1g), Cholesterol 79mg, Sodium 880mg, Carbs 33g (Fiber 8g, Sugars 10g), Protein 24g

**Comment by Flxp49** [comment]
Hi there,

This website does not use the `JSON-LD` schema. Please see #17 for more info. Will close this as it is a duplicate.
