### ISSUE TITLE
Adding the Ability to Increment an Index

### ISSUE THREAD

**Issue by Silet101** [seethroughdev/obsidian-recipe-grabber#5]
Hello, I am loving your extension. For the question, while trying to create a template ran into a bit of snag. I am trying to display the Instructions and wanting them in a numerical list starting from index 1.  
```
{{#each recipeInstructions}}
{{@index}}. {{this.text}}
>
{{/each}}
```
Would it be worth adding a custom helper like the one below to increment the index by 1? Or is there a simpler answer to my issue?
```
var Handlebars = require('handlebars');

Handlebars.registerHelper("inc", function(value, options)
{
    return parseInt(value) + 1;
});
```
```
{{inc @index}}
```
Thank in advance for the help :D

**Comment by seethroughdev** [comment]
Glad you're finding some use with it! 

And interesting question. Is this something that would be solved with an `<ol>`?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

**Comment by Silet101** [comment]
Thank you for the suggestion, I was trying to avoid using HTML and only using CommonMark to have the plain text more human readable with no tags. 

I might just go with what you suggest for how sweet and simple of a solution it is.

**Comment by cathelijne** [comment]
I know this issue is already closed, but there's a handy markdown trick to create numbered lists: just number all items in the list with `1. ` and the parser correctly numbers them.

In my handlebars template, I have:

```
### Instructions

{{#each recipeInstructions}}
1. {{this.text}}
{{/each}}
```

And that outputs numbered lists, starting at 1.
