### ISSUE TITLE
Frontmatter broken

### ISSUE THREAD

**Issue by niposch** [seethroughdev/obsidian-recipe-grabber#6]
in the latest obsidian update (v.1.4.6), which at the time of writing isn't publicly released yet, frontmatters have to be on the first line of the file. Previously, new lines before the frontmatter were okay but now, the frontmatter has to start on the first line.
=> https://obsidian.md/changelog/2023-08-31-desktop-v1.4.6/

The plugin seems to add the extracted text to the end of the file, even when the file is empty, resulting in an empty line before the frontmatter.

As seen here:
![image](https://github.com/seethroughdev/obsidian-recipe-grabber/assets/45246069/9ccd0b66-6462-4726-b0e4-4cd06cb165eb)

**Comment by seethroughdev** [comment]
Thanks @niposch ! Let me see if that's all it is.
