### ISSUE TITLE
Ampersands (&) aren't parsed properly

### ISSUE THREAD

**Issue by illusionistpm** [seethroughdev/obsidian-recipe-grabber#9]
Importing https://www.eatingwell.com/recipe/252591/lemon-dill-chicken/ caused the `&` in both the title and the "salt & pepper" ingredient to show as `&amp;amp;` and `&amp;`, respectively

**Comment by seethroughdev** [comment]
I've changed the default template to use triple handlebars instead ```{{{}}}```. But after testing, it works about half the time for rendering html. In your example, it will not do the heading link. however, it did the ingredient text.

**Comment by seethroughdev** [comment]
Just adding a note here. If you are in preview mode instead of edit mode. all the html snippets do render as expected.
